### PR TITLE
Added !!zgoat

### PR DESCRIPTION
**Pull request by vihanb**
Added a !!zgoat function with help from [this SO answer](http://stackoverflow.com/a/32616807/1620622). This also contains changes from the other branch

### CODE REVIEW

**Comment by schas002** [comment]
The Git Workflow requires to do the thing in a feature branch, regardless of the fork. Also, the function is rather a *Toy*.

**Comment by schas002** [comment]
Oo, how crappy. You replaced the chatbot engine with a compressed version, vandalizing the log. That's bad. Very bad.

**Comment by vihanb** [comment]
@schas002 ...
 1. I'm using a fork of the `develop` branch. This is perfectly fine in the Gitflow Workflow
 2. It looks messy without it minified as browser JS isn't modular you have no other option

> Toy
ಠ__________ಠ

**Comment by vihanb** [comment]
Actually you could load the remote script with jquery i think

**Comment by schas002** [comment]
> ;_; y u haet gaots

I dont haet gaots ಠ_ಠ

Just that the command has no actual use other than having fun.

> I'm using a fork of the `develop` branch. This is OK in the Gitflow Workflow

Declare where is this declared.

> It looks messy without it minified as browser JS has module system

The code in the repo should be clean.

**Comment by schas002** [comment]
Also, the release cycle for release 1 is under way.

**Pull request closed without merging**
